name: CI

#on:
#  workflow_call:
on: [push, pull_request]

jobs:
  test-backend:
    name: Execute Unit tests for Backend Module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compile EJB Module
        run: mvn -B -f ejb-module/pom.xml clean compile test-compile
      - name: Run EJB Module Unit Tests
        run: mvn -B -f ejb-module/pom.xml test

      - name: Compile Backend Module
        run: mvn -B -f backend-module/pom.xml clean compile test-compile
      - name: Run Backend-Module BeneficioEjbIntegrationTest
        run: mvn -B -f backend-module/pom.xml -Dtest=BeneficioEjbIntegrationTest test
      - name: Run Backend-Module BeneficioRepositoryIntegrationTest
        run: mvn -B -f backend-module/pom.xml -Dtest=BeneficioRepositoryIntegrationTest test
      - name: Run Backend-Module BeneficioServiceTest
        run: mvn -B -f backend-module/pom.xml -Dtest=BeneficioServiceTest test
      - name: Run Backend-Module BeneficioControllerTest
        run: mvn -B -f backend-module/pom.xml -Dtest=BeneficioControllerTest test
      - name: Run Backend-Module BackendApplicationTests
        run: mvn -B -f backend-module/pom.xml -Dtest=BackendApplicationTests test

  build-backend:
    runs-on: ubuntu-latest
    needs: [test-backend]
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build backend module
        run: mvn -B -f backend-module/pom.xml clean package -DskipTests
      - name: Run Integration Tests
        run: mvn -B -f backend-module/pom.xml verify
      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v6
        with:
          name: backend-jar
          path: backend-module/target/*.jar
          retention-days: 7
      - name: Upload EJB Artifact
        uses: actions/upload-artifact@v6
        with:
          name: ejb-module-jar
          path: ejb-module/target/*.jar
          retention-days: 7

  build-frontend:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    strategy:
      matrix:
        node-version: [24]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6 # Action to checkout your repository code

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        working-directory: frontend
        run: npm ci 

      - name: Build Angular Application
        working-directory: frontend
        run: npm run build

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v6
        with:
          name: frontend-dist
          path: frontend/dist/
          retention-days: 7

  code-quality:
    name: Code Quality Check (Jococo)
    runs-on: ubuntu-latest
    needs: [build-ejb, build-backend]
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Code Quality Analysis
        run: mvn -B -f backend-module/pom.xml test jacoco:report

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v6
        with:
          name: coverage-report
          path: backend-module/target/site/jacoco/
          retention-dsays: 7
  #zap-scan:
  #  needs: build-project
  #  uses: ./.github/workflows/zap_scan.yml
  #  secrets: inherit
  
  #docker:
  #  needs: zap-scan
  #  uses: ./.github/workflows/Docker.yml
  #  secrets: inherit
  
  #deploy_ecs:
  #  needs: docker
  #  uses: ./.github/workflows/ECS.yml
  #  secrets: inherit