name: Testes CI

on: workflow_dispatch

jobs:

  #test-project:
  #  uses: ./.github/workflows/tests.yml
  #  secrets: inherit

  build-backend:
    #  needs: test-project
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  build-frontend:
    #  needs: test-project
    uses: ./.github/workflows/angular-build.yml
    secrets: inherit

  #zap-scan:
  #  needs: build-project
  #  uses: ./.github/workflows/zap_scan.yml
  #  secrets: inherit

  #docker:
  #  needs: zap-scan
  #  uses: ./.github/workflows/Docker.yml
  #  secrets: inherit
  
  #deploy_ecs:
  #  needs: docker
  #  uses: ./.github/workflows/ECS.yml
  #  secrets: inherit